##Libraries

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import accuracy_score

##importing dataset

In [4]:
df = pd.read_csv('/content/diabetes_012_health_indicators_BRFSS2015.csv')
df.head()

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0

##checking informations

In [5]:
df.shape
df.info()
df.describe()
df.isnull()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198866 entries, 0 to 198865
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Diabetes_012          198866 non-null  float64
 1   HighBP                198866 non-null  float64
 2   HighChol              198866 non-null  float64
 3   CholCheck             198866 non-null  float64
 4   BMI                   198866 non-null  float64
 5   Smoker                198866 non-null  float64
 6   Stroke                198866 non-null  float64
 7   HeartDiseaseorAttack  198866 non-null  float64
 8   PhysActivity          198866 non-null  float64
 9   Fruits                198866 non-null  float64
 10  Veggies               198866 non-null  float64
 11  HvyAlcoholConsump     198866 non-null  float64
 12  AnyHealthcare         198865 non-null  float64
 13  NoDocbcCost           198865 non-null  float64
 14  GenHlth               198865 non-null  float64
 15  MentHlth              198865 non-null  float64
 16  PhysHlth              198865 non-null  float64
 17  DiffWalk              198865 non-null  float64
 18  Sex                   198865 non-null  float64
 19  Age                   198865 non-null  float64
 20  Education             198865 non-null  float64
 21  Income                198865 non-null  float64
dtypes: float64(22)
memory usage: 33.4 MB

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198861,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
198862,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
198863,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
198864,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
198865,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True

##data separating (train,test)

In [6]:
y = df['Diabetes_012']

x = df.drop('Diabetes_012', axis=1)
x.describe()

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
count,198866.000000,198866.000000,198866.000000,198866.000000,198866.000000,198866.000000,198866.000000,198866.000000,198866.000000,198866.000000,...,198865.000000,198865.000000,198865.000000,198865.000000,198865.000000,198865.000000,198865.000000,198865.000000,198865.000000,198865.000000
mean,0.430395,0.425523,0.963272,28.409049,0.450293,0.040771,0.094285,0.755569,0.636061,0.809233,...,0.952098,0.083041,2.504845,3.189355,4.219988,0.168099,0.439640,8.066915,5.058039,6.079893
std,0.495133,0.494423,0.188094,6.725999,0.497524,0.197760,0.292225,0.429750,0.481132,0.392906,...,0.213559,0.275945,1.066159,7.403333,8.694892,0.373955,0.496345,3.044594,0.979618,2.053437
min,0.000000,0.000000,0.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,1.000000,24.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,...,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,6.000000,4.000000,5.000000
50%,0.000000,0.000000,1.000000,27.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,...,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,8.000000,5.000000,7.000000
75%,1.000000,1.000000,1.000000,31.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,...,1.000000,0.000000,3.000000,2.000000,3.000000,0.000000,1.000000,10.000000,6.000000,8.000000
max,1.000000,1.000000,1.000000,98.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,5.000000,30.000000,30.000000,1.000000,1.000000,13.000000,6.000000,8.000000

##Split

In [7]:
x_train,x_test, y_train, y_test = train_test_split(x, y, random_state=1)

##Logistic model

In [ ]:
diabetes_model = LogisticRegression(max_iter=1000)
diabetes_model.fit(x_train, y_train)

##Prediction score

In [ ]:
predictions = diabetes_model.predict(x_test)
test_mae = mean_absolute_error(y_test, predictions)
print('Test score: {}'.format(test_mae))